// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR00Qc8b30uBJcDVn8diaoXgYoiGDSlf8',
    appId: '1:1084929408971:web:aa9b1e651f551a7f6bc04e',
    messagingSenderId: '1084929408971',
    projectId: 'gym-app-6969',
    authDomain: 'gym-app-6969.firebaseapp.com',
    storageBucket: 'gym-app-6969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRQHOUVZX4ubJL40Qr-JUyS6_K1mBtIps',
    appId: '1:1084929408971:android:11760e04469433026bc04e',
    messagingSenderId: '1084929408971',
    projectId: 'gym-app-6969',
    storageBucket: 'gym-app-6969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6h5GCmQ3z9V1SMO2gUnxKH1R4MxOSm7s',
    appId: '1:1084929408971:ios:245623830c1a4d916bc04e',
    messagingSenderId: '1084929408971',
    projectId: 'gym-app-6969',
    storageBucket: 'gym-app-6969.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6h5GCmQ3z9V1SMO2gUnxKH1R4MxOSm7s',
    appId: '1:1084929408971:ios:245623830c1a4d916bc04e',
    messagingSenderId: '1084929408971',
    projectId: 'gym-app-6969',
    storageBucket: 'gym-app-6969.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR00Qc8b30uBJcDVn8diaoXgYoiGDSlf8',
    appId: '1:1084929408971:web:786afec3d1a7f60a6bc04e',
    messagingSenderId: '1084929408971',
    projectId: 'gym-app-6969',
    authDomain: 'gym-app-6969.firebaseapp.com',
    storageBucket: 'gym-app-6969.appspot.com',
  );
}
